from enum import StrEnum


class DisruptionType(StrEnum):
    ROAD_CLOSURE = "ROAD_CLOSURE"
    FACILITY_CLOSURE = "FACILITY_CLOSURE"
    TRANSIT_DISRUPTION = "TRANSIT_DISRUPTION"
    UTILITY_OUTAGE = "UTILITY_OUTAGE"
    WEATHER_NOTICE = "WEATHER_NOTICE"
    OTHER = "OTHER"


class DisruptionSeverity(StrEnum):
    INFO = "INFO"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"


class VerificationStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    VERIFIED = "VERIFIED"
    CONFLICTING = "CONFLICTING"


class SourceKind(StrEnum):
    OFFICIAL_WEB = "OFFICIAL_WEB"
    OFFICIAL_FEED = "OFFICIAL_FEED"
    REPLAY_FIXTURE = "REPLAY_FIXTURE"


class DecisionClassification(StrEnum):
    NO_IMPACT = "NO_IMPACT"
    AUTO_RESOLVABLE = "AUTO_RESOLVABLE"
    HUMAN_DECISION_REQUIRED = "HUMAN_DECISION_REQUIRED"


class IncidentState(StrEnum):
    DETECTED = "DETECTED"
    EXTRACTED = "EXTRACTED"
    VERIFIED = "VERIFIED"
    IMPACT_ASSESSED = "IMPACT_ASSESSED"
    NO_IMPACT = "NO_IMPACT"
    ROUTE_REQUESTED = "ROUTE_REQUESTED"
    CANDIDATE_REJECTED = "CANDIDATE_REJECTED"
    CANDIDATE_VALIDATED = "CANDIDATE_VALIDATED"
    FEASIBLE = "FEASIBLE"
    INFEASIBLE = "INFEASIBLE"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    AUTO_APPROVED = "AUTO_APPROVED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REJECTED = "HUMAN_REJECTED"
    RESOLVED = "RESOLVED"
    OPEN = "OPEN"
